import './globals.css'
import type { Metadata } from 'next'
import { Be_Vietnam_Pro } from 'next/font/google'


const vietnam = Be_Vietnam_Pro({ 
  weight: ['400', '500', '700'],
  variable: '--font-vietnam',
  subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Frontend Mentor | Manage landing page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${vietnam.variable} font-sans`}>
      <body>{children}</body>
    </html>
  )
}
